In [1]:
import numpy as np
import pandas as pd
import re

In [ ]:
import spacy

# Load a pre-trained English NLP model
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading en_core_web_sm model...")
    spacy.cli.download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

In [6]:
df = pd.read_csv("ramayana_shloka_dataset.csv")

In [7]:
text = str(df.iloc[30]['translation'])
text

'"Thereafter, repeatedly turning Bharata back, the elder brother, Rama, gave his wooden shoes to Bharata and entrusting them to represent him \nfor the sake of kingdom. [1-1-37b, 38a]'

In [8]:
import spacy

# Load a pre-trained English NLP model
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading en_core_web_sm model...")
    spacy.cli.download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")


doc = nlp(text)

filtered_tokens = []
in_bracket = False

for token in doc:
    # Check for opening bracket to start skipping
    if token.text == '[':
        in_bracket = True
        continue
    # Check for closing bracket to stop skipping
    if token.text == ']':
        in_bracket = False
        continue

    # If not inside brackets and not a stop word, and not punctuation (unless it's part of a quote)
    if not in_bracket and not token.is_stop and not token.is_punct:
        filtered_tokens.append(token.text)
    elif token.text == '"' or token.text == "'": # Keep quote marks
        filtered_tokens.append(token.text)

# Join the filtered tokens to form the cleaned sentence
# Note: This is a simplified approach to reconstruct the sentence,
# and might not perfectly handle spacing for complex cases.
cleaned_text_nlp = " ".join(filtered_tokens).replace(" .", ".").replace(" ,", ",").replace(" ?", "?").replace(" !", "!")

# Further regex to clean up potential issues from simple join (like " .")
cleaned_text_nlp = re.sub(r'\s([?.!,"](?:\s|$))', r'\1', cleaned_text_nlp)
# Remove potential leading/trailing quotes or other remaining artifacts
cleaned_text_nlp = cleaned_text_nlp.strip().strip("'").strip('"')


print(cleaned_text_nlp)

 repeatedly turning Bharata elder brother Rama gave wooden shoes Bharata entrusting represent
 sake kingdom

In [9]:

def clean_text(text):
    if not isinstance(text, str):  # Handle non-string values
        return ""
    doc = nlp(text)
    filtered_tokens = []
    in_bracket = False

    for token in doc:
        if token.text == '[':
            in_bracket = True
            continue
        if token.text == ']':
            in_bracket = False
            continue
        if not in_bracket and not token.is_stop and not token.is_punct:
            filtered_tokens.append(token.text)
        elif token.text == '"' or token.text == "'":
            filtered_tokens.append(token.text)

    cleaned_text_nlp = " ".join(filtered_tokens).replace(" .", ".").replace(" ,", ",").replace(" ?", "?").replace(" !", "!")
    cleaned_text_nlp = re.sub(r'\s([?.!,"\"](?:\s|$))', r'\1', cleaned_text_nlp)
    cleaned_text_nlp = cleaned_text_nlp.strip().strip("'").strip('"')
    return cleaned_text_nlp

df['clean_translation'] = df['translation'].apply(clean_text)
df[['translation', 'clean_translation']].head()

,translation,clean_translation
0,The ascetic Valmiki inquired Naarada - 'who en...,ascetic Valmiki inquired Naarada ' engaged dee...
1,"""Who really is that person in this present wor...",person present world virtuous vigorous consci...
2,"""Who is appropriate in disposition... who is i...",appropriate disposition interested welfare be...
3,"""Who is that self-composed one, who controlled...",self composed controlled ire brilliant non je...
4,"""All this I wish to listen from you, oh! Great...",wish listen oh Great Sage competent know kind...

In [10]:
df[['translation','clean_translation']].sample(5)

,translation,clean_translation
7939,"""I recognise these flowers that are fallen her...",recognise flowers fallen oh Lakshmana forest ...
1930,"""I am already ready and awaiting for you remai...",ready awaiting remaining Altar Fire Let deter...
4747,"""A son is the most beloved to his mother as he...",son beloved mother born primary \n secondary ...
16523,"""By his penance, Indrajit obtained a weapon ca...",penance Indrajit obtained weapon called Brahm...
17572,"""The course of destiny, when ready to bear fru...",course destiny ready bear fruit diverted \n m...

In [2]:
df.to_csv("first_clean_Sample.csv",index=False)

NameError: name 'df' is not defined

In [3]:
new_df = pd.read_csv("first_clean_Sample.csv")

In [4]:
verse = 28
print(f"{df['clean_translation'][verse]}")
print(f"{df['translation'][verse]}")

NameError: name 'df' is not defined

In [4]:
new_df['shloka'].iloc[12546]

'वज्री महेन्द्रस्त्रिदशेश्वरो वा |\nसाक्षाद्यमो वा वरुणोऽनिलो वा |\nरुद्रोग्निरर्को धनदश्च सोमो |\nन वानरोऽयम् स्वयमेव कालः | ५-५४-३५'

In [5]:
new_df['verse_num_from_shloka'] = new_df['verse_ref'].str.split('-').str[2]
new_df.head()

,Unnamed: 0,kanda_name,sarga,verse_ref,shloka,translation,clean_translation,verse_num_from_shloka
0,0,Bala,1,१-१-१,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,The ascetic Valmiki inquired Naarada - 'who en...,ascetic Valmiki inquired Naarada ' engaged dee...,१
1,1,Bala,1,१-१-२,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,"""Who really is that person in this present wor...",person present world virtuous vigorous consci...,२
2,2,Bala,1,१-१-३,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,"""Who is appropriate in disposition... who is i...",appropriate disposition interested welfare be...,३
3,3,Bala,1,१-१-४,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\...,"""Who is that self-composed one, who controlled...",self composed controlled ire brilliant non je...,४
4,4,Bala,1,१-१-५,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,"""All this I wish to listen from you, oh! Great...",wish listen oh Great Sage competent know kind...,५

In [6]:


def convert_devanagari_to_english(text):
    devanagari_to_english = {
        "०": "0",
        "१": "1",
        "२": "2",
        "३": "3",
        "४": "4",
        "५": "5",
        "६": "6",
        "७": "7",
        "८": "8",
        "९": "9",
    }

    converted_text = ""
    if isinstance(text, str):  # Handle cases where the column might have non-string values (e.g., NaN)
        for char in text:
            if char in devanagari_to_english:
                converted_text += devanagari_to_english[char]
            else:
                converted_text += char
    else:
        converted_text = text  # Return the original value if it's not a string

    return converted_text

In [7]:

new_df["verse_num_from_shloka"] = new_df["verse_num_from_shloka"].apply(convert_devanagari_to_english)

In [8]:
new_df.head()

,Unnamed: 0,kanda_name,sarga,verse_ref,shloka,translation,clean_translation,verse_num_from_shloka
0,0,Bala,1,१-१-१,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,The ascetic Valmiki inquired Naarada - 'who en...,ascetic Valmiki inquired Naarada ' engaged dee...,1
1,1,Bala,1,१-१-२,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,"""Who really is that person in this present wor...",person present world virtuous vigorous consci...,2
2,2,Bala,1,१-१-३,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,"""Who is appropriate in disposition... who is i...",appropriate disposition interested welfare be...,3
3,3,Bala,1,१-१-४,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\...,"""Who is that self-composed one, who controlled...",self composed controlled ire brilliant non je...,4
4,4,Bala,1,१-१-५,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,"""All this I wish to listen from you, oh! Great...",wish listen oh Great Sage competent know kind...,5

In [ ]:

new_df.loc[(new_df['kanda_name'] == 'Bala') & (new_df['sarga'] == 2), 'verse_num_from_shloka']

In [14]:
import pandas as pd
import numpy as np

def fill_nan_incrementally(series):
    filled = []
    last_val = None
    for val in series:
        if pd.isna(val):
            if last_val is not None:
                try:
                    new_val = str(int(last_val) + 1)
                except:
                    new_val = last_val
                filled.append(new_val)
                last_val = new_val
            else:
                filled.append(np.nan)
        else:
            filled.append(val)
            last_val = val
    return pd.Series(filled, index=series.index)

# Apply to each (kanda_name, sarga) group
new_df['verse_num_from_shloka'] = new_df.groupby(['kanda_name', 'sarga'])['verse_num_from_shloka'].transform(fill_nan_incrementally)

In [15]:
# print(new_df[(new_df['kanda_name'] == 'Bala') & (new_df['sarga'] == 2)]['verse_num_from_shloka'])

In [ ]:
# new_df[(new_df['kanda_name'] == 'Bala') & (new_df['sarga'] == 2)].isnull().any()

Unnamed: 0               False
kanda_name               False
sarga                    False
verse_ref                 True
shloka                   False
translation              False
clean_translation        False
verse_num_from_shloka    False
dtype: bool

In [17]:
new_df['verse_num_from_shloka'].isnull().sum()

np.int64(0)

In [22]:
new_df.sample(5)

,Unnamed: 0,kanda_name,sarga,verse_ref,shloka,translation,clean_translation,verse_num_from_shloka
18255,18255,Yuddha,128,६-१२८-६८,छत्रं तस्य च जग्राह शत्रुघ्नः पाण्डुरन् शुभम्,"Shatrughna held over him, a white and charming...",Shatrughna held white charming parasol Sugreev...,68
2135,2135,Ayodhya,2,२-२-५२,स्त्रियो वृद्धास्तरुण्यश्च सायं प्रातः समाहिता...,"""Both young and aged women are praying with a ...",young aged women praying stable mind morning ...,52
5279,5279,Ayodhya,93,२-९३-१५,खुरैर् उदीरितो रेणुर् दिवम् प्रग्च्छाद्य तिष्ठ...,"""The dust raised from the hooves of the horses...",dust raised hooves horses blots heavens wind ...,15
9444,9444,Kishkindha,30,४-३०-१४,ततः चंचूर्य रम्येषु फलार्थी गिरि सानुषु |\nददर...,Meandering on the pleasant mountain-terraces i...,Meandering pleasant mountain terraces search f...,14
9349,9349,Kishkindha,28,३-२८-९,एष फुल्ल अर्जुनः शैलः केतकैः अधिवासितः |\nसुग्...,"""This mountain with fully bloomed Arjuna flowe...",mountain fully bloomed Arjuna flowers fragran...,9

#### This rows remove manually,becuase these translation are not ramayan anymore

#### text like,
#### 1. This is end of chapter.

In [ ]:
# arr = [419, 914, 1019, 5793, 6552, 7644, 7666, 7668, 7669, 7833, 8016, 9327, 10146, 10207, 10208, 10209, 10210, 10211, 10212, 10213, 10214, 10215, 10216, 10217, 10218, 10219, 10220, 10221, 10222, 10223, 10224, 10225, 12591, 15708]

In [ ]:
# list1 = [419, 914, 1019, 5793, 6552, 7644, 7666, 7668, 7669, 7833, 8016, 9327, 10146, 10207, 10208, 10209, 10210, 10211, 10212, 10213, 10214, 10215, 10216, 10217, 10218, 10219, 10220, 10221, 10222, 10223, 10224]

# list2_to_remove = [419, 914, 1019, 1283, 1937, 3269, 3310, 3337, 3398, 3430, 3463, 3500, 3519, 3559, 3609, 3631, 3665, 3687, 3715, 5793, 6202, 6552, 7632, 7633, 7644, 7666, 7668, 7669, 7833, 8016, 9327, 10146, 10207, 10208, 10209, 10210, 10211, 10212, 10213, 10214, 10215, 10216, 10217, 10218, 10219, 10220, 10221, 10222, 10223, 10224, 10225, 10538, 10832, 10860, 10893, 10911, 10919, 10988, 12591, 13637, 14466, 15708]
# # print(len(list2_to_remove))
# # Convert the second list to a set for faster lookup
# set_to_remove = set(list1)

# # Filter out elements from list1 that are present in set_to_remove
# filtered_list = [num for num in list2_to_remove if num not in set_to_remove]

# print(filtered_list)
# # print(len(filtered_list))

[1283, 1937, 3269, 3310, 3337, 3398, 3430, 3463, 3500, 3519, 3559, 3609, 3631, 3665, 3687, 3715, 6202, 7632, 7633, 10225, 10538, 10832, 10860, 10893, 10911, 10919, 10988, 12591, 13637, 14466, 15708]

#### remove the having not use translation for model

In [ ]:
# df.drop(labels=filtered_list)

KeyError: '[1283, 1937, 3269, 3310, 3337, 3398, 3430, 3463, 3500, 3519, 3559, 3609, 3631, 3665, 3687, 3715, 6202, 7632, 7633, 10225, 10538, 10832, 10860, 10893, 10911, 10919, 10988, 12591, 13637, 14466, 15708] not found in axis'

In [23]:
new_df.rename(columns={'verse_num_from_shloka': 'Shloka/Verse'}, inplace=True)

In [24]:
new_df

,Unnamed: 0,kanda_name,sarga,verse_ref,shloka,translation,clean_translation,Shloka/Verse
0,0,Bala,1,१-१-१,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,The ascetic Valmiki inquired Naarada - 'who en...,ascetic Valmiki inquired Naarada ' engaged dee...,1
1,1,Bala,1,१-१-२,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,"""Who really is that person in this present wor...",person present world virtuous vigorous consci...,2
2,2,Bala,1,१-१-३,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,"""Who is appropriate in disposition... who is i...",appropriate disposition interested welfare be...,3
3,3,Bala,1,१-१-४,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\...,"""Who is that self-composed one, who controlled...",self composed controlled ire brilliant non je...,4
4,4,Bala,1,१-१-५,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,"""All this I wish to listen from you, oh! Great...",wish listen oh Great Sage competent know kind...,5
...,...,...,...,...,...,...,...,...
18300,18300,Yuddha,128,६-१२८-१२१,एवमेतत्पुरावृत्तमाख्यानं भद्रमस्तु वः,Tell this epic which occurred long ago in this...,Tell epic occurred long ago manner ask \n fear...,121
18301,18301,Yuddha,128,६-१२८-१२२,देवाश्च सर्वे तुष्यन्ति ग्रहणाच्छ्रवणात्तथा,"By studying and listening to this epic, all th...",studying listening epic gods appeased listenin...,122
18302,18302,Yuddha,128,६-१२८-१२३,भक्त्या रामस्य ये चेमां संहितामृषिणा कृताम्,To those persons who transcribe with devotion ...,persons transcribe devotion collection poems d...,123
18303,18303,Yuddha,128,६-१२८-१२४,कुटुम्बवृद्धिं धनधान्यवृद्धिं |\nस्त्रियश्च मु...,By listening to this highly meaningful and aus...,listening highly meaningful auspicious poetica...,124
18304,18304,Yuddha,128,६-१२८-१२५,आयुष्यमारोग्यकरं यशस्यं |\nसौभ्रातृकं बुद्धिकर...,This narrative is to be listened invariably by...,narrative listened invariably good people seek...,125

In [25]:

new_df = new_df.rename(columns={
    'kanda_name': 'Kanda/Books',
    'sarga': 'Sarga/Chapters',
    'clean_translation': 'English_translation',
})

In [26]:
new_df

,Unnamed: 0,Kanda/Books,Sarga/Chapters,verse_ref,shloka,translation,English_translation,Shloka/Verse
0,0,Bala,1,१-१-१,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,The ascetic Valmiki inquired Naarada - 'who en...,ascetic Valmiki inquired Naarada ' engaged dee...,1
1,1,Bala,1,१-१-२,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,"""Who really is that person in this present wor...",person present world virtuous vigorous consci...,2
2,2,Bala,1,१-१-३,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,"""Who is appropriate in disposition... who is i...",appropriate disposition interested welfare be...,3
3,3,Bala,1,१-१-४,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\...,"""Who is that self-composed one, who controlled...",self composed controlled ire brilliant non je...,4
4,4,Bala,1,१-१-५,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,"""All this I wish to listen from you, oh! Great...",wish listen oh Great Sage competent know kind...,5
...,...,...,...,...,...,...,...,...
18300,18300,Yuddha,128,६-१२८-१२१,एवमेतत्पुरावृत्तमाख्यानं भद्रमस्तु वः,Tell this epic which occurred long ago in this...,Tell epic occurred long ago manner ask \n fear...,121
18301,18301,Yuddha,128,६-१२८-१२२,देवाश्च सर्वे तुष्यन्ति ग्रहणाच्छ्रवणात्तथा,"By studying and listening to this epic, all th...",studying listening epic gods appeased listenin...,122
18302,18302,Yuddha,128,६-१२८-१२३,भक्त्या रामस्य ये चेमां संहितामृषिणा कृताम्,To those persons who transcribe with devotion ...,persons transcribe devotion collection poems d...,123
18303,18303,Yuddha,128,६-१२८-१२४,कुटुम्बवृद्धिं धनधान्यवृद्धिं |\nस्त्रियश्च मु...,By listening to this highly meaningful and aus...,listening highly meaningful auspicious poetica...,124
18304,18304,Yuddha,128,६-१२८-१२५,आयुष्यमारोग्यकरं यशस्यं |\nसौभ्रातृकं बुद्धिकर...,This narrative is to be listened invariably by...,narrative listened invariably good people seek...,125

In [27]:
new_df['verse_ref'] = new_df['Shloka/Verse']

In [30]:
new_df.drop(['Shloka/Verse'],axis=1,inplace=True)

KeyError: "['Shloka/Verse'] not found in axis"

In [31]:
new_df.rename(columns={'verse_ref': 'Shloka/Verse'}, inplace=True)

In [33]:

new_df.drop(['shloka', 'translation'], axis=1, inplace=True)

In [38]:
new_df.head(10)

,Kanda/Books,Sarga/Chapters,Shloka/Verse,English_translation
0,Bala,1,1,ascetic Valmiki inquired Naarada ' engaged dee...
1,Bala,1,2,person present world virtuous vigorous consci...
2,Bala,1,3,appropriate disposition interested welfare be...
3,Bala,1,4,self composed controlled ire brilliant non je...
4,Bala,1,5,wish listen oh Great Sage competent know kind...
5,Bala,1,6,listening words Valmiki Narada knower worlds s...
6,Bala,1,7,Oh Sage Valmiki merits extolled unattainable ...
7,Bala,1,8,emerged Ikshvaku dynasty known people Rama co...
8,Bala,1,9,wise moralist eloquent glorious destroyer ene...
9,Bala,1,10,lion chested concealed collarbones knee lengt...

In [36]:
new_df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [37]:
new_df.to_csv("cleaned_Ramayana_Dataset.csv",index=False)