In [1]:
import numpy as np
import pandas as pd
import re

import spacy

# Load a pre-trained English NLP model
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading en_core_web_sm model...")
    spacy.cli.download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

In [199]:
df = pd.read_csv("ramayana_shloka_dataset.csv")

In [201]:
text = str(df.iloc[30]['translation'])
text

'"Thereafter, repeatedly turning Bharata back, the elder brother, Rama, gave his wooden shoes to Bharata and entrusting them to represent him \nfor the sake of kingdom. [1-1-37b, 38a]'

In [6]:
import spacy

# Load a pre-trained English NLP model
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading en_core_web_sm model...")
    spacy.cli.download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")


doc = nlp(text)

filtered_tokens = []
in_bracket = False

for token in doc:
    # Check for opening bracket to start skipping
    if token.text == '[':
        in_bracket = True
        continue
    # Check for closing bracket to stop skipping
    if token.text == ']':
        in_bracket = False
        continue

    # If not inside brackets and not a stop word, and not punctuation (unless it's part of a quote)
    if not in_bracket and not token.is_stop and not token.is_punct:
        filtered_tokens.append(token.text)
    elif token.text == '"' or token.text == "'": # Keep quote marks
        filtered_tokens.append(token.text)

# Join the filtered tokens to form the cleaned sentence
# Note: This is a simplified approach to reconstruct the sentence,
# and might not perfectly handle spacing for complex cases.
cleaned_text_nlp = " ".join(filtered_tokens).replace(" .", ".").replace(" ,", ",").replace(" ?", "?").replace(" !", "!")

# Further regex to clean up potential issues from simple join (like " .")
cleaned_text_nlp = re.sub(r'\s([?.!,"](?:\s|$))', r'\1', cleaned_text_nlp)
# Remove potential leading/trailing quotes or other remaining artifacts
cleaned_text_nlp = cleaned_text_nlp.strip().strip("'").strip('"')


print(cleaned_text_nlp)

 repeatedly turning Bharata elder brother Rama gave wooden shoes Bharata entrusting represent
 sake kingdom

In [202]:

def clean_text(text):
    if not isinstance(text, str):  # Handle non-string values
        return ""
    doc = nlp(text)
    filtered_tokens = []
    in_bracket = False

    for token in doc:
        if token.text == '[':
            in_bracket = True
            continue
        if token.text == ']':
            in_bracket = False
            continue
        if not in_bracket and not token.is_stop and not token.is_punct:
            filtered_tokens.append(token.text)
        elif token.text == '"' or token.text == "'":
            filtered_tokens.append(token.text)

    cleaned_text_nlp = " ".join(filtered_tokens).replace(" .", ".").replace(" ,", ",").replace(" ?", "?").replace(" !", "!")
    cleaned_text_nlp = re.sub(r'\s([?.!,"\"](?:\s|$))', r'\1', cleaned_text_nlp)
    cleaned_text_nlp = cleaned_text_nlp.strip().strip("'").strip('"')
    return cleaned_text_nlp

df['clean_translation'] = df['translation'].apply(clean_text)
df[['translation', 'clean_translation']].head()

,translation,clean_translation
0,The ascetic Valmiki inquired Naarada - 'who en...,ascetic Valmiki inquired Naarada ' engaged dee...
1,"""Who really is that person in this present wor...",person present world virtuous vigorous consci...
2,"""Who is appropriate in disposition... who is i...",appropriate disposition interested welfare be...
3,"""Who is that self-composed one, who controlled...",self composed controlled ire brilliant non je...
4,"""All this I wish to listen from you, oh! Great...",wish listen oh Great Sage competent know kind...

In [203]:
df[['translation','clean_translation']].sample(5)

,translation,clean_translation
4226,"""In the same way, Rama with tears on his face ...",way Rama tears face joined palms stood \n shi...
15116,"Thereafter, those monkeys who felt rejoiced to...",monkeys felt rejoiced Ravana disconcerted \n a...
16139,"While Lanka was being burnt, the great ocean, ...",Lanka burnt great ocean image reflected \n wat...
906,"""Once there was a highly righteous kingly sage...",highly righteous kingly sage brainchild \n\t\...
13065,"""So many monkeys, endowed with prowess, persev...",monkeys endowed prowess perseverance great st...

In [204]:
verse = 28
print(f"{df['clean_translation'][verse]}")
print(f"{df['translation'][verse]}")

 Bharata possessed worthy way thinking going Rama begged brother Rama great souled
	 truly courageous Bharata spoke words manner Rama" knower probity king"
"That Bharata, possessed of a worthy way of thinking [to get Rama installed as king], on going to Rama, begged his brother Rama, a great souled one and a
	truly courageous one. Bharata spoke words in this manner to Rama - "You alone, the knower of probity, be the king." ... ' [1-1-35, 36a]

In [205]:
df

,Unnamed: 0,kanda_name,sarga,verse_ref,shloka,translation,clean_translation
0,0,Bala,1,१-१-१,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,The ascetic Valmiki inquired Naarada - 'who en...,ascetic Valmiki inquired Naarada ' engaged dee...
1,1,Bala,1,१-१-२,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,"""Who really is that person in this present wor...",person present world virtuous vigorous consci...
2,2,Bala,1,१-१-३,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,"""Who is appropriate in disposition... who is i...",appropriate disposition interested welfare be...
3,3,Bala,1,१-१-४,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\...,"""Who is that self-composed one, who controlled...",self composed controlled ire brilliant non je...
4,4,Bala,1,१-१-५,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,"""All this I wish to listen from you, oh! Great...",wish listen oh Great Sage competent know kind...
...,...,...,...,...,...,...,...
18300,18300,Yuddha,128,६-१२८-१२१,एवमेतत्पुरावृत्तमाख्यानं भद्रमस्तु वः,Tell this epic which occurred long ago in this...,Tell epic occurred long ago manner ask \n fear...
18301,18301,Yuddha,128,६-१२८-१२२,देवाश्च सर्वे तुष्यन्ति ग्रहणाच्छ्रवणात्तथा,"By studying and listening to this epic, all th...",studying listening epic gods appeased listenin...
18302,18302,Yuddha,128,६-१२८-१२३,भक्त्या रामस्य ये चेमां संहितामृषिणा कृताम्,To those persons who transcribe with devotion ...,persons transcribe devotion collection poems d...
18303,18303,Yuddha,128,६-१२८-१२४,कुटुम्बवृद्धिं धनधान्यवृद्धिं |\nस्त्रियश्च मु...,By listening to this highly meaningful and aus...,listening highly meaningful auspicious poetica...
18304,18304,Yuddha,128,६-१२८-१२५,आयुष्यमारोग्यकरं यशस्यं |\nसौभ्रातृकं बुद्धिकर...,This narrative is to be listened invariably by...,narrative listened invariably good people seek...

In [217]:
df = df[['kanda_name','sarga','verse_ref','shloka','clean_translation']]
df.sample(5)

,kanda_name,sarga,verse_ref,shloka,clean_translation
15493,Yuddha,66,६-६६-१९,भग्नानां वो न पश्यामि परिगम्य महीमिमाम्,catch sight place retreated roam \n entire ea...
3381,Ayodhya,34,२-३४-४४,मा विमर्शो वसुमती भरताय प्रदीयताम्,Oh king hesitation offering kingdom Bharata \...
14622,Yuddha,48,६-४८-४,वीर पार्थिव पत्नी त्वम् ये धन्या इति च माम् वि...,Rama slain sooth sayers predicted \n honoured...
13375,Yuddha,10,६-१०-२१,क्रव्यादानाम् मृगाणाम् च पुरीद्वारेषु सज्~घशः ...,city gates heard loud cries carnivorous anima...
2927,Ayodhya,21,२-२१-५२,किम् जीवितेनेह विना त्वया मे |\nलोकेन वा किम् ...,use living world use \n world oblation food o...

In [ ]:
# first verse_number_arabic=Nan at 112
#  last verse_number_arabic=nana at 17925

In [218]:

verse_ref_pattern = r'([०-९]+-[०-९]+-[०-९]+)'

shlokas_series = df['shloka'].astype(str)


extracted_references_df = shlokas_series.str.extractall(verse_ref_pattern)

# Check if any references were found
if not extracted_references_df.empty:
    # Get the Series of extracted references (it's the first captured group, hence column 0)
    extracted_series = extracted_references_df[0]

    # Get unique references and convert to a list for cleaner display
    unique_references = extracted_series.unique().tolist()

    print("Found the following unique verse-like references in the 'shloka' column:")
    if unique_references:
        for ref in unique_references:
            print(ref)
    else:
        # This case should ideally not be hit if extracted_references_df was not empty,
        # but it's a safeguard.
        print("No unique references found after extraction (this is unexpected if matches were found).")
else:
    print("No verse-like references of the pattern 'X-Y-Z' (Devanagari numerals) found in the 'shloka' column.")

No verse-like references of the pattern 'X-Y-Z' (Devanagari numerals) found in the 'shloka' column.

In [219]:
df

,kanda_name,sarga,verse_ref,shloka,clean_translation
0,Bala,1,१-१-१,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,ascetic Valmiki inquired Naarada ' engaged dee...
1,Bala,1,१-१-२,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,person present world virtuous vigorous consci...
2,Bala,1,१-१-३,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,appropriate disposition interested welfare be...
3,Bala,1,१-१-४,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\n...,self composed controlled ire brilliant non je...
4,Bala,1,१-१-५,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,wish listen oh Great Sage competent know kind...
...,...,...,...,...,...
18300,Yuddha,128,६-१२८-१२१,एवमेतत्पुरावृत्तमाख्यानं भद्रमस्तु वः,Tell epic occurred long ago manner ask \n fear...
18301,Yuddha,128,६-१२८-१२२,देवाश्च सर्वे तुष्यन्ति ग्रहणाच्छ्रवणात्तथा,studying listening epic gods appeased listenin...
18302,Yuddha,128,६-१२८-१२३,भक्त्या रामस्य ये चेमां संहितामृषिणा कृताम्,persons transcribe devotion collection poems d...
18303,Yuddha,128,६-१२८-१२४,कुटुम्बवृद्धिं धनधान्यवृद्धिं |\nस्त्रियश्च मु...,listening highly meaningful auspicious poetica...
18304,Yuddha,128,६-१२८-१२५,आयुष्यमारोग्यकरं यशस्यं |\nसौभ्रातृकं बुद्धिकर...,narrative listened invariably good people seek...

In [294]:
# Ensure 'shloka' and 'verse_ref' columns are suitable types
# We assume 'df' is your DataFrame, and 'numpy' (as np) and 'pandas' (as pd) are already imported.
df['shloka'] = df['shloka'].astype(str)
# Convert 'verse_ref' to string as well, handle 'nan' strings by converting to actual NaN
df['verse_ref'] = df['verse_ref'].astype(str).replace('nan', np.nan)

# Define the regex pattern to find Devanagari numerals in X-Y-Z or X-Y format.
# [०-९]+ matches one or more Devanagari digits.
# (?:-[०-९]+)? is an optional non-capturing group for a hyphen followed by digits (handles the third part like -Z).
# The outer parentheses () create a capturing group for the entire pattern.
verse_ref_pattern_extract = r'([०-९]+-[०-९]+(?:-[०-९]+)?)'

# 1. Extract the first embedded reference from 'shloka' into a temporary column.
# expand=False ensures that if there's one capture group, the result is a Series.
df['temp_embedded_ref'] = df['shloka'].str.extract(verse_ref_pattern_extract, expand=False)

# 2. Update 'verse_ref' column ONLY IF 'verse_ref' is currently NaN AND an embedded ref was found.
# This prioritizes existing 'verse_ref' values if they are not NaN.
mask_update_verse_ref = df['verse_ref'].isnull() & df['temp_embedded_ref'].notna()
df.loc[mask_update_verse_ref, 'verse_ref'] = df.loc[mask_update_verse_ref, 'temp_embedded_ref']

# 3. Remove all occurrences of these patterns from the 'shloka' column.
# The same regex pattern is used; str.replace will replace all non-overlapping matches.
df['shloka'] = df['shloka'].str.replace(verse_ref_pattern_extract, '', regex=True)

# 4. Clean up potential extra spaces in 'shloka' after removal.
# Replace multiple consecutive spaces with a single space.
df['shloka'] = df['shloka'].str.replace(r'\s{2,}', ' ', regex=True)
# Remove any leading or trailing whitespace from the 'shloka' column.
df['shloka'] = df['shloka'].str.strip()

# 5. Drop the temporary column as it's no longer needed.
df = df.drop(columns=['temp_embedded_ref'])

print("Processed embedded references in 'shloka' and updated 'verse_ref' where necessary.")
# You can optionally display a few rows where 'verse_ref' was updated:
# print("Rows where 'verse_ref' was updated from 'shloka':")
# print(df[mask_update_verse_ref][['kanda_name', 'sarga', 'shloka', 'verse_ref']].head())
print("-" * 50)

# --- Create Arabic Numeral Verse Reference and Identify Issues ---

# Function to convert Devanagari numeral strings (e.g., '१-२-२७') to Arabic numeral strings (e.g., '1-2-27')
def convert_devanagari_to_arabic_ref(dev_ref):
    if pd.isna(dev_ref):
        return np.nan
    dev_ref_str = str(dev_ref)  # Ensure it's a string
    devanagari_digits = "०१२३४५६७८९"
    arabic_digits = "0123456789"
    translation_table = str.maketrans(devanagari_digits, arabic_digits)
    arabic_ref = dev_ref_str.translate(translation_table)
    # If after translation it's empty, only whitespace, or contains no digits (e.g. if original was just '-'), consider it NaN
    if not arabic_ref.strip() or not any(char.isdigit() for char in arabic_ref):
        return np.nan
    return arabic_ref

# Create the 'verse_number_arabic' column
df['verse_number_arabic'] = df['verse_ref'].apply(convert_devanagari_to_arabic_ref)

# Filter for rows where 'verse_number_arabic' is null
null_verse_arabic_df = df[df['verse_number_arabic'].isnull()]

print("\nRows where 'verse_number_arabic' is null (potential issues):")
if not null_verse_arabic_df.empty:
    # Display relevant columns for rows with null 'verse_number_arabic'
    print(null_verse_arabic_df[['kanda_name', 'sarga', 'verse_ref', 'shloka', 'verse_number_arabic']].head())
else:
    print("No rows found with null 'verse_number_arabic'. All verse references seem to be convertible.")
    
print(f"\nNumber of rows with null 'verse_number_arabic': {len(null_verse_arabic_df)}")

# Display a sample of the DataFrame to see the new column and cleaned 'shloka'
# print("\nSample of DataFrame with 'verse_number_arabic' and cleaned 'shloka':")
# print(df[['kanda_name', 'sarga', 'verse_ref', 'shloka', 'verse_number_arabic']].sample(5))

Processed embedded references in 'shloka' and updated 'verse_ref' where necessary.
--------------------------------------------------

Rows where 'verse_number_arabic' is null (potential issues):
     kanda_name  sarga verse_ref  \
419        Bala     14       NaN
914        Bala     32       NaN
1019       Bala     36       NaN
5793    Ayodhya    110       NaN
6552     Aranya     16       NaN

                                                 shloka verse_number_arabic
419                                                  Or                 NaN
914   धनुषस्तस्य वीर्यं हि जिज्ञासन्तो महीक्षितः |\n...                 NaN
1019  अथ शैलसुता राम त्रिदशानिदमब्रवीत् || २०\nसमन्य...                 NaN
5793  तस्य ज्येष्ठो असि दायादो राम इत्य् अभिविश्रुतः...                 NaN
6552               एक्ष्तोल्लिंग् सेअसोन्स् इन् एपिच्स्                 NaN

Number of rows with null 'verse_number_arabic': 31

In [295]:
df.head()

,kanda_name,sarga,verse_ref,shloka,clean_translation,verse_number_arabic
0,Bala,1,१-१-१,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,ascetic Valmiki inquired Naarada ' engaged dee...,1-1-1
1,Bala,1,१-१-२,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,person present world virtuous vigorous consci...,1-1-2
2,Bala,1,१-१-३,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,appropriate disposition interested welfare be...,1-1-3
3,Bala,1,१-१-४,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\n...,self composed controlled ire brilliant non je...,1-1-4
4,Bala,1,१-१-५,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,wish listen oh Great Sage competent know kind...,1-1-5

In [296]:
df['verse_number_arabic'] = df['verse_number_arabic'].str.split('-').str[2]
df.head()

,kanda_name,sarga,verse_ref,shloka,clean_translation,verse_number_arabic
0,Bala,1,१-१-१,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,ascetic Valmiki inquired Naarada ' engaged dee...,1
1,Bala,1,१-१-२,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,person present world virtuous vigorous consci...,2
2,Bala,1,१-१-३,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,appropriate disposition interested welfare be...,3
3,Bala,1,१-१-४,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\n...,self composed controlled ire brilliant non je...,4
4,Bala,1,१-१-५,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,wish listen oh Great Sage competent know kind...,5

In [221]:
# Inspect the rows where 'verse_number_arabic' is null
print("\n--- Detailed inspection of rows with null 'verse_number_arabic' ---")
if not null_verse_arabic_df.empty:
    print(f"Total problematic rows: {len(null_verse_arabic_df)}\n")
    
    # Display the 'verse_ref' and 'shloka' for a sample of these rows
    # This helps to see if 'verse_ref' is missing, malformed, or if 'shloka' might contain it differently.
    print("Sample of problematic rows (showing 'verse_ref' and 'shloka'):")
    with pd.option_context('display.max_colwidth', 200): # Show more of the shloka text
        print(null_verse_arabic_df[['kanda_name', 'sarga', 'verse_ref', 'shloka']].head(20)) # Show first 20
    
    # Check unique values of 'verse_ref' in these problematic rows
    # This can reveal common problematic patterns or if 'verse_ref' is consistently NaN.
    print("\nUnique 'verse_ref' values in these problematic rows:")
    print(null_verse_arabic_df['verse_ref'].unique())
else:
    print("No rows with null 'verse_number_arabic' to inspect.")

--- Detailed inspection of rows with null 'verse_number_arabic' ---
Total problematic rows: 62

Sample of problematic rows (showing 'verse_ref' and 'shloka'):
     kanda_name  sarga verse_ref  \
419        Bala     14       NaN
914        Bala     32       NaN
1019       Bala     36       NaN
1283       Bala     45       NaN
1937       Bala     73       NaN
3269    Ayodhya     31       NaN
3310    Ayodhya     32       NaN
3337    Ayodhya     33       NaN
3398    Ayodhya     34       NaN
3430    Ayodhya     35       NaN
3463    Ayodhya     36       NaN
3500    Ayodhya     37       NaN
3519    Ayodhya     38       NaN
3559    Ayodhya     39       NaN
3609    Ayodhya     40       NaN
3631    Ayodhya     41       NaN
3665    Ayodhya     42       NaN
3687    Ayodhya     43       NaN
3715    Ayodhya     44       NaN
5793    Ayodhya    110       NaN

                                                                                                   shloka
419                                                                                                    Or
914                   धनुषस्तस्य वीर्यं हि जिज्ञासन्तो महीक्षितः |\nन शेकुरारोपयितुं राजपुत्रा महाबलाः ||
1019                      अथ शैलसुता राम त्रिदशानिदमब्रवीत् || २०\nसमन्युरशपत् सर्वान् क्रोधसंरक्तलोचना |
1283                                         इति वाल्मीकिरामायणे आदिकाव्ये बालकाण्डे पञ्चचत्वारिंशः सर्गः
1937                                                                                                   Or
3269                                       इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे एक त्रिंशः सर्गः
3310                               इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे द्वा त्रयः त्रिंशः सर्गः
3337                                    इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे त्रयः त्रिंशः सर्गः
3398                                    इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे चतुर् त्रिंशः सर्गः
3430                                      इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे पंच त्रिंशः सर्गः
3463                                      इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे षत् त्रिंशः सर्गः
3500                                     इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे सप्त त्रिंशः सर्गः
3519                                    इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे अष्टा त्रिंशः सर्गः
3559                                 इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे एको न चत्वारिंशः सर्गः
3609                                       इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे चत्वारिंशः सर्गः
3631                                     इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे एकचत्वारिंशः सर्गः
3665                                   इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे द्विचत्वारिंशः सर्गः
3687                                   इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे त्रिचत्वारिंशः सर्गः
3715                                  इति वाल्मीकि रामायणे आदि काव्ये अयोध्य काण्डे चतुश्चत्वारिंशः सर्गः
5793  तस्य ज्येष्ठो असि दायादो राम इत्य् अभिविश्रुतः |\nतद् गृहाण स्वकम् राज्यम् अवेक्षस्व जगन् नृप || ३४

Unique 'verse_ref' values in these problematic rows:
[nan]

In [297]:
df[df['verse_number_arabic'].isnull()]

,kanda_name,sarga,verse_ref,shloka,clean_translation,verse_number_arabic
419,Bala,14,NaN,Or,Elderly people sick ones women children dining...,NaN
914,Bala,32,NaN,धनुषस्तस्य वीर्यं हि जिज्ञासन्तो महीक्षितः |\n...,kings inquisitive power bow great mighty prin...,NaN
1019,Bala,36,NaN,अथ शैलसुता राम त्रिदशानिदमब्रवीत् || २०\nसमन्य...,Oh Rama daughter Himalayan Mountain Uma \n\t\...,NaN
2635,Ayodhya,14,२-१४,ततः स राजा तम् सूतम् सन्न हर्षः सुतम् प्रति |\...,king pious glorious having lost joy son looked...,NaN
3133,Ayodhya,27,२-२७१४,सह त्वया गमिश्यामि वसमद्य न संशयः |\nनाहम् शक्...,Today doubt come forest Oh illustrious \n int...,NaN
5793,Ayodhya,110,NaN,तस्य ज्येष्ठो असि दायादो राम इत्य् अभिविश्रुतः...,eldest son Dasaratha known Rama heir \n claim...,NaN
6552,Aranya,16,NaN,एक्ष्तोल्लिंग् सेअसोन्स् इन् एपिच्स्,portrayal seasons epics delicacies \n disputed...,NaN
6585,Aranya,18,३-१८,समृद्ध अर्थस्य सिद्धार्था मुदित अमल वर्णिनी |\...,Oh goggle eyed befitting complexion un staina...,NaN
7644,Aranya,53,NaN,ओर्,time death mortals wish enjoy noxious non rec...,NaN
7666,Aranya,54,NaN,ओर्,going city Lanka symmetrized roadways entered ...,NaN
7668,Aranya,54,NaN,ओर्,Ravana placed Seetha eyelashes blackish deep \...,NaN
7669,Aranya,54,NaN,ओर्,Ravana placed Seetha eyelashes blackish deep \...,NaN
7833,Aranya,60,NaN,ओर्,Oh Rose apple tree thou seest Seetha thou kno...,NaN
8016,Aranya,66,NaN,ओर्,Oh best Ikshvaku s oh Rama contemplate divine...,NaN
9194,Kishkindha,24,४-२४,सोदर्य अघाता अपर गात्र वालः संताप हस्त अक्षि श...,sin killing brother assumed form elephant sin...,NaN
9327,Kishkindha,27,NaN,ओर्,master worlds undertake certain tasks \n achi...,NaN
10146,Kishkindha,51,NaN,ओर्,practising ascesis thousands years horrendous...,NaN
10207,Kishkindha,54,NaN,तथा ब्रुवति तारे तु तारा अधिपति वर्चसि |\nअथ म...,Lt Tara resplendence similar moonshine spoken ...,NaN
10208,Kishkindha,54,NaN,बुद्ध्या हि अष्ट अंगया युक्तम् चतुर् बल समन्वि...,Hanuma considered Vali son Angada having eight...,NaN
10209,Kishkindha,54,NaN,आपूर्यमाणम् शश्वत् च तेजो बल पराक्रमैः |\nशशिन...,Angada steadily brimming spiritedness mightine...,NaN
10210,Kishkindha,54,NaN,स चतुर्णाम् उपायानाम् तृतीयम् उपवर्णयन् |\nभेद...,Hanuma rhetorically started schismatic secessi...,NaN
10211,Kishkindha,54,NaN,तेषु सर्वेषु भिन्नेषु ततो अभीषय अंगदम् |\nभीषण...,Hanuma vanaras defect Angada idea defecting Su...,NaN
10212,Kishkindha,54,NaN,त्वम् समर्थ तरः पित्रा युद्धे तारेय वै ध्रुवम्...,father undeniably abler warfare oh son Lady T...,NaN
10213,Kishkindha,54,NaN,नित्यम् अस्थिर चित्ता हि कपयो हरि पुंगव |\nन आ...,Oh best monkey Angada monkeys inconsistent Se...,NaN
10214,Kishkindha,54,NaN,त्वाम् न एते हि अनुयुंजेयुः प्रत्यक्षम् प्रवदा...,plainly tell obvious Jambavanta monkeys like ...,NaN
10215,Kishkindha,54,NaN,विगृह्य आसनम् अपि आहुः दुर्बलेन बलीयसा |\nआत्म...,mightless odds mighty linger speak guard \n m...,NaN
10216,Kishkindha,54,NaN,याम् च इमाम् मन्यसे धात्रीम् एतत् बिलम् इति श्...,matter going underground Black Hole suppose h...,NaN
10217,Kishkindha,54,NaN,स्वल्पम् हि कृतम् इन्द्रेण क्षिपता हि अशनिम् प...,Indra thudded Thunderbolt underground illusor...,NaN
10218,Kishkindha,54,NaN,लक्ष्मणस्य च नाराचा बहवः सन्ति तत् विधाः |\nवज...,numerous ironarrows Lakshmana kindred Thunder...,NaN
10219,Kishkindha,54,NaN,अवस्थाने यदा एव त्वम् आसिष्यसि परंतप |\nतदा एव...,settle underground unbefitting place crown pr...,NaN
10220,Kishkindha,54,NaN,स्मरंतः पुत्र दाराणाम् नित्य उद्विग्ना बुभुक्ष...,sulking reminiscing sons wives hungered proxi...,NaN
10221,Kishkindha,54,NaN,स त्वम् हीनः सुहृद्भिः च हित कामैः च बंधुभिः |...,Devoid goodhearted friends wellwishing relati...,NaN
10222,Kishkindha,54,NaN,अति उग्र वेगा निशिता घोरा लक्ष्मण सायकाः |\nअप...,far fiercely frantic arrows Lakshmana targete...,NaN
10223,Kishkindha,54,NaN,अस्माभिः तु गतम् सार्धम् विनीतवत् उपस्थितम् |\...,return Kishkindha obediently Sugreeva flanker...,NaN
10224,Kishkindha,54,NaN,धर्म राजः पितृव्यः ते प्रीति कामो दृढ व्रतः |\...,paternaluncle Sugreeva gleam honesty free dis...,NaN
10715,Sundara,1,५-१९८,यस्य त्वेतानि चत्वारि वानरेन्द्र यथा तव || धृत...,O best Vanaras qualities courage vision intel...,NaN
11269,Sundara,17,५-१७,ततः कुमुदषण्डाभो निर्मलम् निर्मलोदयः |\nप्रजगा...,moon peaceful rise radiance equaling group lot...,NaN
15808,Yuddha,70,६-७०,विषाणम् च अस्य निष्कृष्य वालि पुत्रो महा बलः |...,Pulling tusk elephant battle mighty Angada ran...,NaN
15997,Yuddha,73,६-७३,स सम्प्राप्य महातेजा युद्धभूमिमरिन्दमः || - २०...,Reaching battle field Indrajit great splendour...,NaN
15998,Yuddha,73,६-७३,ततस्तु हुतभोक्तारं हुतभुक्सदृशप्रभः || - २१\nज...,foremost demons having radiance equal fire \n ...,NaN
16032,Yuddha,73,६-७३,ते केवलं सन्ददृशुः शिताग्रान् |\nबाणान्रणे वान...,monkeys battle saw arrows pointed tips falling...,NaN

In [230]:
# Add this to a new cell

if not null_verse_arabic_df.empty:
    problematic_indices = null_verse_arabic_df.index.tolist()
    print(f"\n--- Index values of the {len(problematic_indices)} rows with null 'verse_number_arabic' ---")
    print(problematic_indices)
    
    # If you want to see them one per line for easier reading:
    # print("\nIndices (one per line):")
    # for idx in problematic_indices:
    #     print(idx)
else:
    print("No rows with null 'verse_number_arabic' to get indices from.")

--- Index values of the 62 rows with null 'verse_number_arabic' ---
[419, 914, 1019, 1283, 1937, 3269, 3310, 3337, 3398, 3430, 3463, 3500, 3519, 3559, 3609, 3631, 3665, 3687, 3715, 5793, 6202, 6552, 7632, 7633, 7644, 7666, 7668, 7669, 7833, 8016, 9327, 10146, 10207, 10208, 10209, 10210, 10211, 10212, 10213, 10214, 10215, 10216, 10217, 10218, 10219, 10220, 10221, 10222, 10223, 10224, 10225, 10538, 10832, 10860, 10893, 10911, 10919, 10988, 12591, 13637, 14466, 15708]

In [ ]:
arr = [419, 914, 1019, 5793, 6552, 7644, 7666, 7668, 7669, 7833, 8016, 9327, 10146, 10207, 10208, 10209, 10210, 10211, 10212, 10213, 10214, 10215, 10216, 10217, 10218, 10219, 10220, 10221, 10222, 10223, 10224, 10225, 12591, 15708]

In [285]:
list1 = [419, 914, 1019, 5793, 6552, 7644, 7666, 7668, 7669, 7833, 8016, 9327, 10146, 10207, 10208, 10209, 10210, 10211, 10212, 10213, 10214, 10215, 10216, 10217, 10218, 10219, 10220, 10221, 10222, 10223, 10224]

list2_to_remove = [419, 914, 1019, 1283, 1937, 3269, 3310, 3337, 3398, 3430, 3463, 3500, 3519, 3559, 3609, 3631, 3665, 3687, 3715, 5793, 6202, 6552, 7632, 7633, 7644, 7666, 7668, 7669, 7833, 8016, 9327, 10146, 10207, 10208, 10209, 10210, 10211, 10212, 10213, 10214, 10215, 10216, 10217, 10218, 10219, 10220, 10221, 10222, 10223, 10224, 10225, 10538, 10832, 10860, 10893, 10911, 10919, 10988, 12591, 13637, 14466, 15708]
# print(len(list2_to_remove))
# Convert the second list to a set for faster lookup
set_to_remove = set(list1)

# Filter out elements from list1 that are present in set_to_remove
filtered_list = [num for num in list2_to_remove if num not in set_to_remove]

print(filtered_list)
# print(len(filtered_list))

[1283, 1937, 3269, 3310, 3337, 3398, 3430, 3463, 3500, 3519, 3559, 3609, 3631, 3665, 3687, 3715, 6202, 7632, 7633, 10225, 10538, 10832, 10860, 10893, 10911, 10919, 10988, 12591, 13637, 14466, 15708]

#### remove the having not use translation for model

In [ ]:
df.drop(labels=filtered_list)

KeyError: '[1283, 1937, 3269, 3310, 3337, 3398, 3430, 3463, 3500, 3519, 3559, 3609, 3631, 3665, 3687, 3715, 6202, 7632, 7633, 10225, 10538, 10832, 10860, 10893, 10911, 10919, 10988, 12591, 13637, 14466, 15708] not found in axis'

In [298]:
df

,kanda_name,sarga,verse_ref,shloka,clean_translation,verse_number_arabic
0,Bala,1,१-१-१,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,ascetic Valmiki inquired Naarada ' engaged dee...,1
1,Bala,1,१-१-२,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,person present world virtuous vigorous consci...,2
2,Bala,1,१-१-३,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,appropriate disposition interested welfare be...,3
3,Bala,1,१-१-४,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\n...,self composed controlled ire brilliant non je...,4
4,Bala,1,१-१-५,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,wish listen oh Great Sage competent know kind...,5
...,...,...,...,...,...,...
18300,Yuddha,128,६-१२८-१२१,एवमेतत्पुरावृत्तमाख्यानं भद्रमस्तु वः,Tell epic occurred long ago manner ask \n fear...,121
18301,Yuddha,128,६-१२८-१२२,देवाश्च सर्वे तुष्यन्ति ग्रहणाच्छ्रवणात्तथा,studying listening epic gods appeased listenin...,122
18302,Yuddha,128,६-१२८-१२३,भक्त्या रामस्य ये चेमां संहितामृषिणा कृताम्,persons transcribe devotion collection poems d...,123
18303,Yuddha,128,६-१२८-१२४,कुटुम्बवृद्धिं धनधान्यवृद्धिं |\nस्त्रियश्च मु...,listening highly meaningful auspicious poetica...,124
18304,Yuddha,128,६-१२८-१२५,आयुष्यमारोग्यकरं यशस्यं |\nसौभ्रातृकं बुद्धिकर...,narrative listened invariably good people seek...,125

In [299]:
df.drop('verse_ref',axis=1,inplace=True)

In [300]:
df

,kanda_name,sarga,shloka,clean_translation,verse_number_arabic
0,Bala,1,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,ascetic Valmiki inquired Naarada ' engaged dee...,1
1,Bala,1,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,person present world virtuous vigorous consci...,2
2,Bala,1,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,appropriate disposition interested welfare be...,3
3,Bala,1,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\n...,self composed controlled ire brilliant non je...,4
4,Bala,1,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,wish listen oh Great Sage competent know kind...,5
...,...,...,...,...,...
18300,Yuddha,128,एवमेतत्पुरावृत्तमाख्यानं भद्रमस्तु वः,Tell epic occurred long ago manner ask \n fear...,121
18301,Yuddha,128,देवाश्च सर्वे तुष्यन्ति ग्रहणाच्छ्रवणात्तथा,studying listening epic gods appeased listenin...,122
18302,Yuddha,128,भक्त्या रामस्य ये चेमां संहितामृषिणा कृताम्,persons transcribe devotion collection poems d...,123
18303,Yuddha,128,कुटुम्बवृद्धिं धनधान्यवृद्धिं |\nस्त्रियश्च मु...,listening highly meaningful auspicious poetica...,124
18304,Yuddha,128,आयुष्यमारोग्यकरं यशस्यं |\nसौभ्रातृकं बुद्धिकर...,narrative listened invariably good people seek...,125

In [303]:
df.rename(columns={'shloka': 'Shloka/Verse'}, inplace=True)

In [306]:
df.drop('verse_number_arabic',axis=1,inplace=True)

In [307]:
df

,kanda_name,sarga,Shloka/Verse,clean_translation
0,Bala,1,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,ascetic Valmiki inquired Naarada ' engaged dee...
1,Bala,1,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,person present world virtuous vigorous consci...
2,Bala,1,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,appropriate disposition interested welfare be...
3,Bala,1,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\n...,self composed controlled ire brilliant non je...
4,Bala,1,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,wish listen oh Great Sage competent know kind...
...,...,...,...,...
18300,Yuddha,128,एवमेतत्पुरावृत्तमाख्यानं भद्रमस्तु वः,Tell epic occurred long ago manner ask \n fear...
18301,Yuddha,128,देवाश्च सर्वे तुष्यन्ति ग्रहणाच्छ्रवणात्तथा,studying listening epic gods appeased listenin...
18302,Yuddha,128,भक्त्या रामस्य ये चेमां संहितामृषिणा कृताम्,persons transcribe devotion collection poems d...
18303,Yuddha,128,कुटुम्बवृद्धिं धनधान्यवृद्धिं |\nस्त्रियश्च मु...,listening highly meaningful auspicious poetica...
18304,Yuddha,128,आयुष्यमारोग्यकरं यशस्यं |\nसौभ्रातृकं बुद्धिकर...,narrative listened invariably good people seek...

In [312]:
df.rename(columns={'English_translation/Verse': 'English_translation'}, inplace=True)

In [321]:
df

,kanda_name,sarga,Shloka/Verse,English_translation
0,Bala,1,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,ascetic Valmiki inquired Naarada ' engaged dee...
1,Bala,1,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,person present world virtuous vigorous consci...
2,Bala,1,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,appropriate disposition interested welfare be...
3,Bala,1,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\n...,self composed controlled ire brilliant non je...
4,Bala,1,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,wish listen oh Great Sage competent know kind...
...,...,...,...,...
18300,Yuddha,128,एवमेतत्पुरावृत्तमाख्यानं भद्रमस्तु वः,Tell epic occurred long ago manner ask \n fear...
18301,Yuddha,128,देवाश्च सर्वे तुष्यन्ति ग्रहणाच्छ्रवणात्तथा,studying listening epic gods appeased listenin...
18302,Yuddha,128,भक्त्या रामस्य ये चेमां संहितामृषिणा कृताम्,persons transcribe devotion collection poems d...
18303,Yuddha,128,कुटुम्बवृद्धिं धनधान्यवृद्धिं |\nस्त्रियश्च मु...,listening highly meaningful auspicious poetica...
18304,Yuddha,128,आयुष्यमारोग्यकरं यशस्यं |\nसौभ्रातृकं बुद्धिकर...,narrative listened invariably good people seek...

In [322]:
df.rename(columns={'kanda_name': 'Kanda/Book'}, inplace=True)
df.rename(columns={'sarga': 'Sarga/Chapter'}, inplace=True)

In [323]:
df

,Kanda/Book,Sarga/Chapter,Shloka/Verse,English_translation
0,Bala,1,तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम् |\nनार...,ascetic Valmiki inquired Naarada ' engaged dee...
1,Bala,1,को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्य...,person present world virtuous vigorous consci...
2,Bala,1,चारित्रेण च को युक्तः सर्वभूतेषु को हितः |\nवि...,appropriate disposition interested welfare be...
3,Bala,1,आत्मवान् को जितक्रोधो द्युतिमान् कोऽनसूयकः |\n...,self composed controlled ire brilliant non je...
4,Bala,1,एतदिच्छाम्यहं श्रोतुं परं कौतूहलं हि मे |\nमहर...,wish listen oh Great Sage competent know kind...
...,...,...,...,...
18300,Yuddha,128,एवमेतत्पुरावृत्तमाख्यानं भद्रमस्तु वः,Tell epic occurred long ago manner ask \n fear...
18301,Yuddha,128,देवाश्च सर्वे तुष्यन्ति ग्रहणाच्छ्रवणात्तथा,studying listening epic gods appeased listenin...
18302,Yuddha,128,भक्त्या रामस्य ये चेमां संहितामृषिणा कृताम्,persons transcribe devotion collection poems d...
18303,Yuddha,128,कुटुम्बवृद्धिं धनधान्यवृद्धिं |\nस्त्रियश्च मु...,listening highly meaningful auspicious poetica...
18304,Yuddha,128,आयुष्यमारोग्यकरं यशस्यं |\nसौभ्रातृकं बुद्धिकर...,narrative listened invariably good people seek...

In [324]:
df.to_csv("cleaned_Ramayana_Dataset.csv",index=False)